library(pdftools)
library(wordcloud)
library(tm)
loc ="C:\\Users\\Savleen Kaur\\Downloads\\state-of-aging-in-allegheny-county-report.pdf"
txt = pdf_text(loc)
cat(txt[15])
txt_corpus=Corpus(VectorSource(txt))
txt_corpus= tm_map(txt_corpus,tolower)
txt_corpus= tm_map(txt_corpus,removePunctuation)
txt_corpus= tm_map(txt_corpus,stripWhitespace)
head(stopwords("en"))
txt_corpus= tm_map(txt_corpus,removeWords,stopwords("en"))
txt_corpus$content
dtm= DocumentTermMatrix(txt_corpus)
dtm=as.matrix(dtm)
View(dtm)
dtm=t(dtm)
occu=rowSums(dtm)
no_occu=sort(occu,decreasing = TRUE)
head(no_occu)
wordcloud(head(names(no_occu),30),head(no_occu,30), scale=c(2,1))