#----------How to remove values in vectors
vec <- c(87,34,56,78)
vec <- vec[vec!=56]
print(vec)

#----------deleting series
vec2<- 1:10
vec2<- vec2[!vec2 %in% 3:7]
vec2[-c(3,8)]
vec2[-2]

#--------replacing with other number
vec3<- c(12,13,14,15,16)
vec3[length(vec3)-4]=90
vec3
vec3[6]=56

#--------Replacing with NA
vec4<- c(56,45,34,23,98,76,87,09,39)
vec4[2]=NA
vec4
vec4[c(3,4)]=NA
is.na(vec4)
vec4[!is.na(vec4)]


#-----Vector Indexing
letters[1:3]
letters[ c(2,4,6) ]
LETTERS[1:3]
LETTERS[ c(2,4,6) ]

#-----A logical vector
x <- 1:10
x[ (x > 5) ]
x[ (x%%2==0) ]
x[ (x%%2==1) ]

#----------To find Maximum number generated by runif having Na
vect<-1:500
vect[runif(100,1,500)]<- NA
max(vect)
max(na.omit(vect))
max(vect, na.rm=TRUE)

letters[1:5]
rep(letters[1:9], times=2)
seq()

#---aww aww aww
rep(letters[c(1,23,23)], times=3)
rep(letters[seq(from=1,to=10, by=2)],times=2)

